apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: mymetallb-ip-pool
      protocol: layer2
      addresses:
      - 10.211.55.241-10.211.55.250
