apiVersion: v1
kind: Service
metadata:
  name: myecho-svc-loadbalancer
spec:
  ports:
  - name: myecho-svcport
    port: 8886
    targetPort: 80
  selector:
    app: myecho
    dev: stage
  type: LoadBalancer
