apiVersion: v1
kind: Service
metadata:
  name: myecho-svc-clusterip
spec:
  ports:
  - name: myecho-svcport
    port: 8888
    targetPort: 80
  selector:
    app: myecho
    dev: stage
  type: ClusterIP
