apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: functions.example.com
spec:
  group: example.com
  version: v1
  scope: Namespaced
  names:
    kind: Function
    plural: functions
